#!/usr/bin/env bash
set -eux

# preflight node stuff
jlpm --ignore-optional --prefer-offline
jlpm lint
jlpm build

# install labextension in editable mode
jupyter labextension develop --overwrite .

# install python package
python -m pip install -e . --no-deps --ignore-installed -v

# manually enable extension
jupyter serverextension enable --py jupyterlab_pullrequests
jupyter server extension enable --py jupyterlab_pullrequests

# verify install
jupyter labextension list
jupyter server extension list
